site_name: AI Minesweeper Discovery Framework
site_url: https://<your-gh-pages-url>
repo_url: https://github.com/GenghisDarb/AI-Minesweeper-Discovery-Framework
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
extra_css:
  - css/custom_palette.css
  - css/badges.css
nav:
  - Home: index.md
  - Fractal Demo: torus_brot_demo.md
  - Meta-Cell Guide: meta_cell_usage.md
  - Ï‡-Tests:
      - Prime Residue: prime_residue.md
      - Confidence Oscillation: confidence_osc.md
