site_name: AI Minesweeper Discovery Framework
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - Tutorials:
      - Element Discovery: tutorials/element_discovery.md
  - API Reference: api.md
