site_name: AI Minesweeper Discovery Framework
site_url: https://genghisdarb.github.io/AI-Minesweeper-Discovery-Framework/
repo_url: https://github.com/GenghisDarb/AI-Minesweeper-Discovery-Framework
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
extra_css:
  - css/custom_palette.css
  - css/badges.css
nav:
  - Home: index.md
  - Fractal Demo: torus_brot_demo.md
  - Meta-Cell Guide:
      - Meta-Cell Confidence Design: docs/design_meta_cell.md
      - Ï‡-Tests:
          - Prime Residue: prime_residue.md
          - Confidence Oscillation: confidence_osc.md
  - Validations:
      - Gravitational Wave Phase A: gw_validation.md
      - Prime Spiral Phase B: prime_spirals.md
      - Bicycle Ghost Rider: bicycle_validation.md
  - Drafts:
      - LLM Backends: LLM_backends.md
      - Contributor Guide: contributor_guide.md
      - Roadmap Overview: roadmap_overview.md
