site_name: AI Minesweeper Discovery Framework
site_url: https://genghisdarb.github.io/AI-Minesweeper-Discovery-Framework/
repo_url: https://github.com/GenghisDarb/AI-Minesweeper-Discovery-Framework
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
extra_css:
  - css/custom_palette.css
  - css/badges.css
nav:
  - Home: index.md
  - Tutorials:
      - Discovering phi-phase reset: tutorials/discovering_phi_phase_reset.md
      - Element discovery: tutorials/element_discovery.md
      - Prime residue recursion: tutorials/prime_residue_recursion.md
  - Theory:
      - Torus-of-tori and DPP-14: torus_of_tori_and_dpp14.md
      - Fractal Demo: torus_brot_demo.md
      - Meta-Cell Guide: meta_cell_usage.md
      - Ï‡-Tests:
          - Prime Residue: prime_residue.md
          - Confidence Oscillation: confidence_osc.md
