[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "ai-minesweeper"
version = "1.0.0"
description = "AI Minesweeper Game"
authors = [
    { name = "Your Name", email = "your@email.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
dependencies = [
    "pandas",
    "pytest"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "ruff>=0.0.285",
    "mypy>=1.0",
    "coverage>=7.0",
    "typer"
]

[project.scripts]
minesweeper = "ai_minesweeper.cli:app"

[tool.ruff]
exclude = ["notebooks"]

