name: CI

on:
  push:
    branches: [ main, "release/**" ]
  pull_request:
    branches: [ main, "release/**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pip-audit

      - name: Lint (ruff autofix + format + verify)
        run: |
          ruff check . --fix
          ruff format .
          ruff check .

      - name: Security audit (non-blocking)
        run: |
          pip-audit -r requirements.txt || true

      - name: Run tests
        env:
          AIMS_TEST_MODE: "1"
          AIMS_LLM_PROVIDER: "disabled"
          MPLBACKEND: "Agg"
        run: |
          pytest -q
