name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Lint with ruff
        run: ruff check src tests
      - name: Run tests with coverage
        run: pytest --cov=src

  streamlit-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Streamlit smoke test
        run: |
          streamlit run streamlit_app.py --server.headless true &
          sleep 5
          curl -sSf http://localhost:8501/ > /dev/null
