name: Release

on:
	push:
		tags:
			- "v*"

jobs:
	build-publish:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Setup Python
				uses: actions/setup-python@v5
				with:
					python-version: "3.11"

			- name: Build dists
				run: |
					python -m pip install --upgrade pip
					pip install build twine
					python -m build
					twine check dist/*

			# - name: Publish to PyPI
			#   env:
			#     TWINE_USERNAME: __token__
			#     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
			#   run: twine upload dist/*

