name: Build-Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install mkdocs deps
        run: |
          pip install --upgrade pip
          pip install \
            mkdocs-material==9.5.* \
            mkdocs-git-revision-date-localized-plugin==1.2.* \
            mkdocs-autorefs==1.3.1 \
            mkdocstrings[python]==0.24.* \
            griffe==0.34.*
          pip install mkdocs-redirects==1.1.0

      - name: Install TeX (subset)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build static site (MkDocs)
        run: mkdocs build --verbose

      - name: Build whitepaper PDF
        run: |
          pip install -r requirements.txt
          python scripts/build_whitepage.py || echo "PDF generation failed gracefully."

      - name: Echo build artifact location
        run: echo "MkDocs site built in ./site (not deployed)"

      - name: Verify Streamlit installed
        run: python -c "import streamlit; print('Streamlit is installed')"
