name: Build-Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # we only read from repo
      pages: write            # needed by deploy-pages

    steps:
      - uses: actions/checkout@v4

      - name: Install mkdocs deps
        run: |
          pip install --upgrade pip
          pip install \
            mkdocs-material==9.5.* \
            mkdocs-git-revision-date-localized-plugin==1.2.* \
            mkdocstrings[python]==0.24.*

      - name: Verify CODECOV_TOKEN
        run: |
          if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "::error::CODECOV_TOKEN missing – add under Settings → Secrets → Actions"
            exit 1
          fi

      - name: Install TinyTeX (pdflatex)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended

      - name: Install XeLaTeX (xelatex fallback)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Build static site (MkDocs)
        # compiles markdown in /docs into site/
        run: mkdocs build --strict --verbose

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          path: site

      - name: Echo site URL
        if: steps.deploy.outputs.page_url != ''
        run: echo "🟢 Docs available at ${{ steps.deploy.outputs.page_url }}"
