name: Build-Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # REQUIRED for gh-pages deploy
      pages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install mkdocs deps
        run: |
          pip install --upgrade pip
          pip install \
            mkdocs-material==9.5.* \
            mkdocs-git-revision-date-localized-plugin==1.2.* \
            mkdocs-autorefs==1.3.1 \
            mkdocstrings[python]==0.24.* \
            griffe==0.34.*
          # Ensure all dependencies for building docs are installed
          pip install mkdocs-redirects==1.1.0

      - name: Install TinyTeX (pdflatex)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended
          # Ensure additional LaTeX packages are available
          sudo apt-get install -y texlive-science texlive-latex-extra

      - name: Install XeLaTeX (xelatex fallback)
        run: sudo apt-get update && sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build static site (MkDocs)
        # compiles markdown in /docs into site/
        run: mkdocs build --strict --verbose

      - name: Build whitepaper PDF
        run: |
          # Ensure the whitepaper script has all dependencies
          pip install -r requirements.txt
          python scripts/build_whitepage.py || echo "PDF generation failed gracefully."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: site

      - name: Echo site URL
        run: echo "🟢 Docs available at https://genghisdarb.github.io/AI-Minesweeper-Discovery-Framework/"

      - name: Verify Streamlit installed
        run: python -c "import streamlit; print('✅ Streamlit is installed')"

      - name: Clear pip cache (optional)
        run: pip cache purge
