name: Nightly Batch

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check configuration flag
        run: |
          if [ "$USE_WOLFRAM" != "true" ]; then
            echo "Skipping Wolfram scripts – using pre-generated files."
            exit 0
          fi

      - name: Skip Wolfram batch execution
        if: runner.os != 'Windows'
        run: echo "Skipping Wolfram scripts – no engine"

      - name: Commit results
        run: |
          echo "Committing batch results..."
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/*.txt data/*.csv data/*.json figures/*.png reports/*.csv || true
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Nightly auto-batch output"
            git push
          fi
